haahshsha

diff --git a/.github/actions/amongus/action.yml b/.github/actions/amongus/action.yml
--- a/.github/actions/amongus/action.yml
+++ b/.github/actions/amongus/action.yml
@@ -7,6 +7,8 @@ runs:
       shell: bash
       run: |
         echo "an error is sus..."
+        sudo apt-get update -qq && sudo apt-get install -y chafa
+        echo "generating error output..."
         echo "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣤⣤⣤⣤⣤⣶⣦⣤⣄⡀⠀⠀⠀⠀⠀⠀⠀⠀"
         echo "⠀⠀⠀⠀⠀⠀⠀⠀⢀⣴⣿⡿⠛⠉⠙⠛⠛⠛⠛⠻⢿⣿⣷⣤⡀⠀⠀⠀⠀⠀"
         echo "⠀⠀⠀⠀⠀⠀⠀⠀⣼⣿⠋⠀⠀⠀⠀⠀⠀⠀⢀⣀⣀⠈⢻⣿⣿⡄⠀⠀⠀⠀"
@@ -26,3 +28,10 @@ runs:
         echo "⠀⠀⠀⠀⠀⠀⠀⣿⣿⠀⠀⠀⠀⠀⣿⣿⡇⠀⢹⣿⡆⠀⠀⠀⣸⣿⠇⠀⠀⠀"
         echo "⠀⠀⠀⠀⠀⠀⠀⢿⣿⣦⣄⣀⣠⣴⣿⣿⠁⠀⠈⠻⣿⣿⣿⣿⡿⠏⠀⠀⠀⠀"
         echo "⠀⠀⠀⠀⠀⠀⠀⠈⠛⠻⠿⠿⠿⠿⠋⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"
+        echo ""
+        echo "Displaying the cause of the error..."
+        echo ""
+        chafa 14-rickroll.jpg --size 80x40
+        echo ""
+        echo "BUILD FAILED - GET BETTER"
+        exit 1
